# Optimized configuration for high-performance facial recognition
# Key optimizations:
# - Lower resolution for better throughput
# - Balanced detection/recognition intervals
# - GPU acceleration enabled
# - Improved thresholds for accuracy

[pipeline]
display=1
is_aarch64=1
known_face_dir="data/known_faces"
save_feature_path="data/features"
save_feature=0
realtime=1

[streammux]
gpu_id=0
batch-size=8                    # = number of sources (if all active simultaneously)
# Optimized: Reduced resolution for 2x better throughput while maintaining detection quality
width=960                       # Reduced from 1920 (YOLOv8n works well at lower res)
height=540                      # Reduced from 1080
# Optimized: Lower latency settings
batched-push-timeout=20000      # 20ms for aggressive real-time processing
enable-padding=1                # Maintain aspect ratio
#nvbuf-memory-type=0            # default (0: system, 2: device). On NX keep 0 for stability
live-source=1                   # Important for RTSP streams
#sync-inputs=1                  # Do not wait for slow sources

[nvosd]
process-mode=0
display-text=1

[source]
"621ca2e007e648f898099597a078bccd" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/501"
"625d66f10a0b4a0a920be73f705773bd" = "rtsp://admin:wesmart!@192.168.0.243:554/Unicast/channels/101"
"6a887f101a204b3788e45b9d4cbcb84b" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/601"
"93efaf1091cc4b83990619a17347879f" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/801"
"c0fad364fd7345b1af2fe5a2f691e7f7" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/701"
"c9bb715db20a489f94f58d36bb3602d0" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/301"
"d73cf20e2aa544b7b352070f24bff721" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/401"

[pgie]
# YOLOv8n face detection with optimized settings
config-file-path="config/config_yolov8n_face_optimized.txt"

[sgie]
# ArcFace recognition with optimized settings
config-file-path="config/config_arcface_optimized.txt"

[tracker]
config-file-path="config/config_tracker_perf.txt"

[tiler]
width=1920
height=1080
enable-padding=1

[sink]
qos=1
sync=0

[recognition]
# Optimized: Higher threshold for better precision (reduces false positives)
threshold=0.65
# Directory to save recognized face images
save_dir="data/faces/recognized"
# Save mode: "first" saves only first detection per track (optimal for performance)
save_mode="first"
# Backend: FAISS for proven performance
backend="faiss"
feature_dir="data/known_faces"

# Vector index configuration - Optimized for performance
use_index=1
metric="cosine"
# Use IVF for better performance with large galleries (>1000 faces)
index_type="ivf"
# Enable GPU acceleration for significant speedup
use_gpu=1
gpu_id=0

# IVF configuration for large-scale recognition
nlist=100                       # Coarse quantization cells (auto if 0)
m_pq=0                         # PQ compression (disabled for accuracy)
nbits_pq=8

# Index persistence
index_path="data/index/faiss_optimized.index"
labels_path="data/index/labels_optimized.json"

# Live indexing disabled for performance
index_stream=0
stream_index_path="data/index/live_optimized.index"
stream_labels_path="data/index/live_labels_optimized.json"

# Recognize once per track for efficiency
recognize_once_per_track=1

[debug]
# Reduced verbosity for performance
verbose=0

# Performance tuning thresholds
[thresholds]
# PGIE (YOLOv8n) minimum confidence
pgie_min_conf=0.55

# Additional optimizations
[optimizations]
# Enable frame dropping for real-time performance
enable_frame_dropping=1
# Queue management
max_queue_size=3
# Memory management
use_nvmm=1