[pipeline]
display=0
is_aarch64=1
known_face_dir="data/known_faces"
save_feature_path="data/features"
save_feature=0

[streammux]
gpu_id=0
batch-size=1
width=1920
height=1080
batched-push-timeout=1000

[nvosd]
process-mode=0
display-text=1

[source]
source0="file:///home/m2n/edge-deepstream/data/media/friends_s1e1_cut.mp4"
#source1="file:///opt/nvidia/deepstream/deepstream-6.3/sources/face-recognition-deepstream/data/media/friends_s1e1_whole.mp4"

[pgie]
#config-file-path="config/config_retinaface.txt"
config-file-path="config/config_yolov8n_face.txt"

[sgie]
config-file-path="config/config_arcface.txt"

[tracker]
config-file-path="config/config_tracker_perf.txt"

[tiler]
width=1920
height=1080

[sink]
qos=1
sync=0

# Recognition tuning
[recognition]
# Cosine similarity threshold for accepting a match (higher = stricter)
threshold=0.4
# Directory to save recognized face images
save_dir="data/faces/recognized"
# Save mode for recognized images: "all" (every frame), "first" (first per track), "best" (best score per track)
save_mode="none"

[debug]
# Verbose console prints (matching per-frame)
verbose=0
