[pipeline]
display=1
is_aarch64=1
known_face_dir="data/known_faces"
save_feature_path="data/features"
save_feature=0
realtime=1

[streammux]
gpu_id=0
batch-size=8                    
width=640                       
height=640                      
batched-push-timeout=40000      # Reduced from 40ms to 25ms (40 FPS target)
sync-inputs=0                   # Keep async - don't wait for slow sources
live-source=1                   # Force live-source mode for all streams
attach-sys-ts=0                 # Don't attach system timestamps (reduces processing)
buffer-pool-size=4              # Reduce buffer pool size (default is 16)

[nvosd]
process-mode=0
display-text=1

[source]
"1" = "rtsp://admin:wesmart!@192.168.0.243:554/Unicast/channels/101"
"2" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/801"
"3" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/701"
"4" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/601"
"5" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/501"
"6" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/401"
"7" = "rtsp://admin:123456Aa@192.168.0.213:1554/Streaming/Channels/301"
"8" = "rtsp://admin:wesmart!@192.168.0.243:554/Unicast/channels/101"

[pgie]
config-file-path="config/config_yolov8n_face_realtime.txt"

[sgie]
config-file-path="config/config_arcface_realtime.txt"

[tracker]
config-file-path="config/config_tracker_perf.txt"

[tiler]
width=1920
height=1080
# Add these for better performance
show-source=0                   # Disable source info overlay
buffer-pool-size=4              # Reduce buffer pool

[sink]
qos=1                          # Enable QoS (Quality of Service)
sync=1                         # Enable sync for proper pacing
async=0                        # Disable async for lower latency
max-lateness=16666666         # Allow 16ms max lateness (60fps)
throttle-time=0               # Disable throttling

[recognition]
threshold=0.5
save_dir="data/faces/recognized"
save_mode="first"
backend="faiss"
feature_dir="data/known_faces"
use_index=1
metric="cosine"
index_type="flat"
use_gpu=0
gpu_id=0
nlist=0
m_pq=0
nbits_pq=8
index_path="data/index/faiss.index"
labels_path="data/index/labels.json"
index_stream=0
index_mode="per_track"
index_label="name"
stream_index_path="data/index/live.index"
stream_labels_path="data/index/live_labels.json"
recognize_once_per_track=1

[debug]
verbose=0

[thresholds]
pgie_min_conf=0.6

[events]
enable=0
unix_socket="/tmp/my_socket"
send_image=1

[mqtt]
host = "localhost"
port = 1883
request_topic = "/local/core/v2/ai/request"
response_topic = "/local/core/v2/ai/response"