[pipeline]
display=1
is_aarch64=1
known_face_dir="data/known_faces"
save_feature_path="data/features"
save_feature=0
realtime=1

[streammux]
gpu_id=0
batch-size=1
width=640
height=640
batched-push-timeout=30000
sync-inputs=0

[nvosd]
process-mode=0
display-text=1

[source]
# Replace host if accessing remotely
"local_rtsp" = "rtsp://127.0.0.1:8554/test"

[pgie]
config-file-path="config/config_yolov8n_face.txt"

[sgie]
config-file-path="config/config_arcface.txt"

[tracker]
config-file-path="config/config_tracker_perf.txt"

[tiler]
width=640
height=640

[sink]
qos=1
sync=1

[recognition]
threshold=0.5
save_dir="data/faces/recognized"
save_mode="first"
backend="faiss"
feature_dir="data/known_faces"
use_index=1
metric="cosine"
index_type="flat"
use_gpu=0
gpu_id=0
nlist=0
m_pq=0
nbits_pq=8
index_path="data/index/faiss.index"
labels_path="data/index/labels.json"
index_stream=0
index_mode="per_track"
index_label="name"
stream_index_path="data/index/live.index"
stream_labels_path="data/index/live_labels.json"
recognize_once_per_track=1

[debug]
verbose=1

[thresholds]
pgie_min_conf=0.5

[events]
enable=1
unix_socket="/tmp/my_socket"
send_image=1

[mqtt]
host = "localhost"
port = 1883
request_topic = "/local/core/v2/ai/request"
response_topic = "/local/core/v2/ai/response"
